### PR TITLE
LiteX Driver Development

### PR DESCRIPTION
**Pull request by NateMeyer**
Update implementation for the LiteX Thunderscope driver.

### CODE REVIEW

**Comment by NateMeyer** [comment]
I would like to get this PR updated and merged in soon so we can stay in sync.  Do you have any preference on how we package the tslitex.dll with this?  Currently I've been building it separately and copying the dll into the ts.net.engine build folder.  Alternatively, we could add the libtslitex repo as a submodule here and integrate that build into your build scripts.

As for updates, I need to go through what's changed in the driver interface recently, add the calibration handling, and finish implementing the device list/query.

**Comment by macaba** [comment]
Ideally there would be a Action on your repository to build the DLL and then that can be copied into this repo as-is.
For now, could you put an x64 DLL in the source/TS.NET/Drivers/LiteX/Interop directory? The csproj can be modified to always copy this to the build directory.

**Comment by NateMeyer** [comment]
I'm not a fan of adding binaries to git.  If I set up a build action for the libtslitex repo, You think you would want your build script to just download the DLL from a Github release package? 

Right now I'm thinking to merge this with the current functionality (after we decide on the DLL inclusion above) and I'll start a new branch for building up the configuration get/set path.

**Comment by NateMeyer** [comment]
For now, I just added handling not to delete the library file if one is present.  For now I think we can rely on manually installing it during development.  It should only be needed if configured to use the LiteX HardwareDriver in the yaml.

**Comment by macaba** [comment]
Looks good! I'm looking forwards to try it out.

**Pull request merged**
